version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/project
    ports:
      - 8001:8001
    env_file:
      - .env
    restart: always
